import { SidebarType } from 'types';

export const SIDEBAR_MENU: SidebarType[] = [
  { label: 'Avatar', to: '/avatar' },
  { label: 'Alert', to: '/alert' },
  { label: 'Button', to: '/button' },
  { label: 'Badge', to: '/badge' },
  { label: 'Checkbox', to: '/checkbox' },
  { label: 'Drawer', to: '/drawer' },
  { label: 'Images', to: '/image' },
  { label: 'Grid Layout', to: '/grid-layout' },
  { label: 'Grid System', to: '/grid-system' },
  { label: 'Icon', to: '/icon' },
  { label: 'Logo', to: '/logo' },
  { label: 'Loader', to: '/loader' },
  { label: 'Modal', to: '/modal' },
  { label: 'Radio', to: '/radio' },
  { label: 'Select', to: '/select' },
  { label: 'Skeleton', to: '/skeleton' },
  { label: 'Snackbars', to: '/snackbars' },
  { label: 'Tag', to: '/tag' },
  { label: 'TextField', to: '/textfield' },
  { label: 'Tooltip', to: '/tooltip' },
  { label: 'Toogle', to: '/toogle' },
];
